-- MySQL Script generated by MySQL Workbench
-- Fri Dec  5 01:39:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema adega
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adega` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `adega` ;

-- -----------------------------------------------------
-- Table `adega`.`vinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adega`.`vinho` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `produtor` VARCHAR(50) NOT NULL,
  `pais_origem` VARCHAR(25) NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NULL DEFAULT NULL,
  `uva_casta` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `adega`.`garrafa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adega`.`garrafa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_vinho` INT NOT NULL,
  `safra` YEAR NOT NULL,
  `preco_compra` DECIMAL(10,2) NOT NULL,
  `data_aquisicao` DATE NOT NULL,
  `consumida` TINYINT(1) NULL DEFAULT '0',
  `data_consumo` DATE NULL DEFAULT NULL,
  `avaliacao` DECIMAL(3,1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `garrafa_ibfk_1` (`id_vinho` ASC) VISIBLE,
  CONSTRAINT `garrafa_ibfk_1`
    FOREIGN KEY (`id_vinho`)
    REFERENCES `adega`.`vinho` (`id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `adega`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adega`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
